#!/usr/bin/env bash
# A bash script that displays;
# To infinity and beyond indefinitely,
# With a sleep 2 in between each iteration.
# I am invincible!!! when it receives a SIGTERM signal. This means the script should not terminate immediately upon receiving SIGTERM, but instead print this message and continue its loop.

trap 'echo "I am invincible!!!"' SIGTERM

while true
do
  echo "To infinity and beyond"
  sleep 2
done
