#!/usr/bin/env bash
# This script implements a case statement within a while loop to display different messages based on specific loop iteration numbers

i=1

while [ $i -le 20 ]
do
  case $i in
    4)
      echo "4"
      echo "bad luck from China"
      ;;
    9)
      echo "9"
      echo "bad luck from Japan"
      ;;
    17)
      echo "17"
      echo "bad luck from Italy"
      ;;
    *)
      echo "$i"
      ;;
  esac
  i=$((i + 1))
done
